/*
 * This task is a bit harder than the previous two.
 * Feel free to change the E3SLinqProvider and any other classes if needed.
 * Possibly, after these changes you will need to rewrite existing tests to make them work again =).
 *
 * The task: implement support of && operator for IQueryable. The final request generated by FTSRequestGenerator, should
 * imply the following rules: https://kb.epam.com/display/EPME3SDEV/Telescope+public+REST+for+data#TelescopepublicRESTfordata-FTSRequestSyntax
 */

using System;
using System.Linq;
using System.Linq.Expressions;
using Expressions.Task3.E3SQueryProvider.Models.Entities;
using Xunit;

namespace Expressions.Task3.E3SQueryProvider.Test
{
    public class E3SAndOperatorSupportTests
    {
        #region SubTask 3: AND operator support

        [Fact]
        public void TestAndQueryable()
        {
            var translator = new ExpressionToFtsRequestTranslator();
            Expression<Func<IQueryable<EmployeeEntity>, IQueryable<EmployeeEntity>>> expression
                = query => query.Where(e => e.Workstation == "EPRUIZHW006" && e.Manager.StartsWith("John"));
            /*
             * The expression above should be converted to the following FTSQueryRequest and then serialized inside FTSRequestGenerator:
             * "statements": [
                { "query":"Workstation:(EPRUIZHW006)"},
                { "query":"Manager:(John*)"}
                // Operator between queries is AND, in other words result set will fit to both statements above
              ],
             */
            var expectedResult = "\"statements\": [ { \"query\":\"Workstation:(EPRUIZHW006)\" }, { \"query\":\"Manager:(John*)\" } ]";
            string translated = translator.Translate(expression);
            Assert.Equal(expectedResult, translated);
        }

        [Fact]
        public void TestAndQueryableWithThreeParams()
        {
            var translator = new ExpressionToFtsRequestTranslator();
            Expression<Func<IQueryable<EmployeeEntity>, IQueryable<EmployeeEntity>>> expression
                = query => query.Where(e => e.Workstation == "EPRUIZHW006" && e.Manager.StartsWith("John") && e.Status == "DONE");
            /*
             * The expression above should be converted to the following FTSQueryRequest and then serialized inside FTSRequestGenerator:
             * "statements": [
                { "query":"Workstation:(EPRUIZHW006)"},
                { "query":"Manager:(John*)"}
                // Operator between queries is AND, in other words result set will fit to both statements above
              ],
             */
            var expectedResult = "\"statements\": [ { \"query\":\"Workstation:(EPRUIZHW006)\" }, { \"query\":\"Manager:(John*)\" }, { \"query\":\"Status:(DONE)\" } ]";
            string translated = translator.Translate(expression);
            Assert.Equal(expectedResult, translated);
        }

        [Fact]
        public void TestAndQueryableWithFourParams()
        {
            var translator = new ExpressionToFtsRequestTranslator();
            Expression<Func<IQueryable<EmployeeEntity>, IQueryable<EmployeeEntity>>> expression
                = query => query.Where(e => e.Workstation == "EPRUIZHW006" && e.Manager.StartsWith("John") && e.Status.Equals("DONE") && e.Superior.StartsWith("1"));
            /*
             * The expression above should be converted to the following FTSQueryRequest and then serialized inside FTSRequestGenerator:
             * "statements": [
                { "query":"Workstation:(EPRUIZHW006)"},
                { "query":"Manager:(John*)"}
                // Operator between queries is AND, in other words result set will fit to both statements above
              ],
             */
            var expectedResult = "\"statements\": [ { \"query\":\"Workstation:(EPRUIZHW006)\" }, { \"query\":\"Manager:(John*)\" }, { \"query\":\"Status:(DONE)\" }, { \"query\":\"Superior:(1*)\" } ]";
            string translated = translator.Translate(expression);
            Assert.Equal(expectedResult, translated);
        }

        #endregion
    }
}
